# Generated by Django 3.2.5 on 2021-07-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Image',
            field=models.ImageField(default='asdfg', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
